services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    container_name: env_monitoring_db
    environment:
      - POSTGRES_DB=env_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"  # 5433:5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  timescaledb_data: