version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sensebox-db
    environment:
      POSTGRES_DB: env_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: sensebox-fetcher
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: env_monitoring
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  db_data:
